apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  application.secret.properties: |
    YWRtaW4= # Base64 encoded value for "admin"
    password: MWYyZDFlMmU2N2Rm # Base64 encoded value for "1f2d1e2e67df"